runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_dir: frontend/build

skip_files:
- frontend/node_modules
- frontend/public
- frontend/src
- frontend/package.json